### ISSUE TITLE
Update needed: This codealong describes behavior not seen by students

### ISSUE THREAD

**Issue by kkterai** [learn-co-students/javascript-logging-v-000#1]
I recommend updating the text and images to reflect what students can expect.

![Screen Shot 2019-06-21 at 11 53 51 AM](https://user-images.githubusercontent.com/19792273/59947754-ed25ff00-9422-11e9-8400-d43540c592e2.png)

![Screen Shot 2019-06-21 at 11 54 22 AM](https://user-images.githubusercontent.com/19792273/59947755-ed25ff00-9422-11e9-98ff-9ba40ed4edc3.png)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
